spring.application.name=ejercicio

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL en consola y configuración de DDL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# SA q jdbc:h2:mem:5cd7c04e-1aa1-44b4-b025-eb63db412aec